//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteCrudAppWithImagesInDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class employe
    {
        public int id { get; set; }
        [DisplayName("Name")]
        [Required(ErrorMessage ="Name is Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Image")]
        public string image_path { get; set; }

        public HttpPostedFileBase imageFile { get; set; }
    }
}
